# Generated by Django 4.2 on 2024-03-23 09:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('uid', models.CharField(default=uuid.UUID('5b35cd61-3d82-4d8c-b946-b3635624fc79'), max_length=36, primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=30, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.CharField(default=uuid.UUID('70e8a552-908f-47a4-84d2-a40363565bd0'), max_length=36, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('password', models.TextField()),
                ('phone', models.CharField(db_index=True, max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='roles', to='apps.userrole')),
            ],
        ),
    ]
