# Generated by Django 4.2 on 2024-03-23 09:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default=uuid.UUID('28a3c18b-359e-4c74-91d7-54d1a74c4ea5'), max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='uid',
            field=models.CharField(default=uuid.UUID('96d901b7-e2e3-4beb-8d63-6ecf96cc656b'), max_length=36, primary_key=True, serialize=False),
        ),
    ]
