# Generated by Django 4.2 on 2024-03-24 03:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_user_uid_alter_userrole_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('uid', models.CharField(default=uuid.UUID('51e860cb-67ef-453a-b815-302004c7712d'), max_length=36, primary_key=True, serialize=False)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default=uuid.UUID('4857f876-26d7-43b1-bc5b-a011a6fec2dc'), max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='uid',
            field=models.CharField(default=uuid.UUID('e3ef655d-6ce4-43d8-b10c-78b1e9a98d72'), max_length=36, primary_key=True, serialize=False),
        ),
    ]
