# Generated by Django 4.2 on 2024-03-24 03:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_useraddress_alter_user_uid_alter_userrole_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='users', to='apps.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default=uuid.UUID('3ec1e359-b125-4c8c-8abd-e9ee0819ff95'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='uid',
            field=models.CharField(default=uuid.UUID('949e4881-233c-4bd8-ba29-571e5c83bb3d'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='uid',
            field=models.CharField(default=uuid.UUID('49009aab-8428-43af-ab4f-10d9d9ce7a3b'), max_length=100, primary_key=True, serialize=False),
        ),
    ]
