# Generated by Django 4.2 on 2024-03-24 04:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_useraddress_user_alter_user_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='address', to='apps.userrole'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default=uuid.UUID('95fb4e80-a803-468a-8067-0d3387298aa6'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='uid',
            field=models.CharField(default=uuid.UUID('f2ffdcff-b31e-4261-a603-1d9610cc4c3f'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='uid',
            field=models.CharField(default=uuid.UUID('9ae5540a-049f-483f-b27e-fc9383c47370'), max_length=100, primary_key=True, serialize=False),
        ),
    ]
