# Generated by Django 4.2 on 2024-03-24 04:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_alter_user_role_alter_user_uid_alter_useraddress_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='roles', to='apps.userrole'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default=uuid.UUID('87285c08-21fe-402f-b135-16722d4d0e5c'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='uid',
            field=models.CharField(default=uuid.UUID('ad762fc6-6661-47e5-8b5b-901076c3d1bc'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='users_address', to='apps.user'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='uid',
            field=models.CharField(default=uuid.UUID('b8bcd0d1-f71b-4b8f-8a92-b10769faa36e'), max_length=100, primary_key=True, serialize=False),
        ),
    ]
