# Generated by Django 4.2 on 2024-03-24 16:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_productcategory_productdiscount_productinventory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('uid', models.CharField(default=uuid.UUID('829c9839-dcab-40ae-8085-a0d621352c8b'), max_length=100, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('razorpay_order_id', models.CharField(max_length=100)),
                ('razorpay_payment_id', models.CharField(max_length=100)),
                ('razorpay_signature', models.CharField(max_length=100)),
                ('amount', models.PositiveBigIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='ProductOrderToDeliveryStatus',
            fields=[
                ('uid', models.CharField(default=uuid.UUID('59c25ffe-644c-4c47-aa00-b731b73846b6'), max_length=100, primary_key=True, serialize=False)),
                ('step_name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(default=None)),
                ('deleted_at', models.DateTimeField(default=None)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='uid',
            field=models.CharField(default=uuid.UUID('4e45b193-4325-468e-a1d8-4a96b12b64c6'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='uid',
            field=models.CharField(default=uuid.UUID('278420c1-acb2-4927-8864-63bdcd82948d'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='uid',
            field=models.CharField(default=uuid.UUID('0dc57ffc-0329-4f5f-9adf-e2aaefe855c4'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='uid',
            field=models.CharField(default=uuid.UUID('80f8865a-497e-4530-b1f4-b8b8612d0503'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default=uuid.UUID('9b21700f-7c68-4f17-8525-d03b5c07a930'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='uid',
            field=models.CharField(default=uuid.UUID('3ce12c28-20ef-45b4-9281-b2b9f587ae98'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='uid',
            field=models.CharField(default=uuid.UUID('bed72361-04ed-46b4-89b5-677dfff906cf'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('uid', models.CharField(default=uuid.UUID('4377a142-ba62-432c-97cd-9855ed8ba6ab'), max_length=100, primary_key=True, serialize=False)),
                ('order_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('order_quantity', models.PositiveIntegerField()),
                ('order_total_price', models.PositiveBigIntegerField()),
                ('is_accepted_by_customer', models.BooleanField(default=False)),
                ('otp_for_verify', models.CharField(max_length=6)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(default=None)),
                ('order_payment', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment_order', to='apps.payment')),
                ('order_status', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='status_order', to='apps.productordertodeliverystatus')),
                ('product', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_orders', to='apps.product')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_orders', to='apps.user')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('uid', models.CharField(default=uuid.UUID('e5a5fa18-c680-46d4-8b77-af2af63f8cbb'), max_length=100, primary_key=True, serialize=False)),
                ('cart_quantity', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(default=None)),
                ('product', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='product_carts', to='apps.product')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_carts', to='apps.user')),
            ],
        ),
    ]
