# Generated by Django 4.2 on 2024-03-25 03:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_payment_productordertodeliverystatus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('uid', models.CharField(default=uuid.UUID('e6414b26-696c-4adc-be61-f261dbe80052'), max_length=100, primary_key=True, serialize=False)),
                ('invoice_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('invoice', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(default=None)),
            ],
        ),
        migrations.AddField(
            model_name='cartitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_sent_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='order',
            name='is_invoice_send',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='otp_expiry',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='uid',
            field=models.CharField(default=uuid.UUID('d80323be-9140-44e3-a154-38829eb17c01'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='uid',
            field=models.CharField(default=uuid.UUID('cb07d50e-7828-485d-8cf1-141462ad9a97'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='uid',
            field=models.CharField(default=uuid.UUID('5e00006d-31bd-449b-93f8-27c2d589a1f3'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='uid',
            field=models.CharField(default=uuid.UUID('d2cee304-8992-4c1b-9107-33d22151bae8'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='uid',
            field=models.CharField(default=uuid.UUID('95aef5ca-c9b9-4734-9df1-98301d779b16'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='uid',
            field=models.CharField(default=uuid.UUID('c209fe22-708d-4636-98ae-302af3cc2b5b'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='uid',
            field=models.CharField(default=uuid.UUID('a0e7486d-6ae8-44e2-a44f-e308378ec1be'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productordertodeliverystatus',
            name='uid',
            field=models.CharField(default=uuid.UUID('0d2f4725-fe37-4f60-b9b5-d89a5abf0ca8'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default=uuid.UUID('9c3e6c30-ad97-4b24-997f-5169f8597607'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='uid',
            field=models.CharField(default=uuid.UUID('846805af-1adc-41c8-b1c6-b785682bc927'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='uid',
            field=models.CharField(default=uuid.UUID('6048ab5c-284d-49f9-bef2-7740c8400778'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='ProductAttachment',
            fields=[
                ('uid', models.CharField(default=uuid.UUID('bbaa1755-090a-4504-8c28-ccd8944a5ba9'), max_length=100, primary_key=True, serialize=False)),
                ('attachment_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('file_type', models.CharField(max_length=100)),
                ('file', models.CharField(max_length=255)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(default=None)),
                ('deleted_at', models.DateTimeField(default=None)),
                ('product', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='product_attachment', to='apps.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_invoice',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='invoice_order', to='apps.invoice'),
        ),
    ]
