# Generated by Django 4.2 on 2024-03-27 04:57

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_alter_cartitem_uid_alter_invoice_uid_alter_order_uid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('uid', models.CharField(default=uuid.UUID('976ac9a8-8cc8-4d8d-b906-f5c440626d8d'), max_length=100, primary_key=True, serialize=False)),
                ('error_message', models.TextField()),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('user_type', models.CharField(blank=True, max_length=255, null=True)),
                ('request_method', models.CharField(blank=True, max_length=255, null=True)),
                ('request_headers', models.CharField(blank=True, max_length=255, null=True)),
                ('request_parameters', models.CharField(blank=True, max_length=255, null=True)),
                ('request_body', models.CharField(blank=True, max_length=255, null=True)),
                ('client_ip', models.CharField(blank=True, max_length=255, null=True)),
                ('stack_trace', models.TextField()),
                ('exception_type', models.CharField(blank=True, max_length=255, null=True)),
                ('view_name', models.CharField(blank=True, max_length=255, null=True)),
                ('response_status_code', models.CharField(blank=True, max_length=255, null=True)),
                ('enviroment', models.CharField(blank=True, max_length=255, null=True)),
                ('error_location', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='uid',
            field=models.CharField(default=uuid.UUID('354af244-2310-40a5-8540-089b6e9d7d37'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='uid',
            field=models.CharField(default=uuid.UUID('3f66102b-9cb8-47cc-a114-bab2930ffa69'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='uid',
            field=models.CharField(default=uuid.UUID('6a577ea0-d2ba-4634-8e4f-dda809c372f2'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='uid',
            field=models.CharField(default=uuid.UUID('28a8ea33-28c2-4f50-8048-87cd68becb57'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='uid',
            field=models.CharField(default=uuid.UUID('61ebe033-2b9a-40ed-888f-0a70f6b6df37'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productattachment',
            name='uid',
            field=models.CharField(default=uuid.UUID('8dafff88-1d24-48f7-bb78-5502f7d55f43'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='uid',
            field=models.CharField(default=uuid.UUID('90ffb48c-7da5-4cd9-bd45-88cd308bbd72'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='uid',
            field=models.CharField(default=uuid.UUID('a53e333d-25bf-4706-b3fa-f2c200b5a9ef'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='uid',
            field=models.CharField(default=uuid.UUID('4cd22e84-ba31-49d5-93b7-3dc449d15a6d'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productordertodeliverystatus',
            name='uid',
            field=models.CharField(default=uuid.UUID('c498a3f5-db68-4407-bcd3-5743c767d797'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default=uuid.UUID('d817ab6b-6233-479b-adeb-9eadbd71ab89'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='uid',
            field=models.CharField(default=uuid.UUID('a91d2f67-7fab-4c9d-ac12-051ce7248b7f'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='uid',
            field=models.CharField(default=uuid.UUID('71a747f1-0e22-4860-96f1-1544f4b138bd'), max_length=100, primary_key=True, serialize=False),
        ),
    ]
