# Generated by Django 4.2 on 2024-03-27 05:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_errorlog_alter_cartitem_uid_alter_invoice_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='uid',
            field=models.CharField(default=uuid.UUID('3098f4b7-39df-4200-aeea-50748617440b'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='request_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='request_headers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='uid',
            field=models.CharField(default=uuid.UUID('1b4fb33a-bae0-45a1-a00c-4bbc21cd0f99'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='uid',
            field=models.CharField(default=uuid.UUID('16b2e736-ff0f-43a4-99d8-0a01415a1e67'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='uid',
            field=models.CharField(default=uuid.UUID('f1d6f48d-e798-4976-8b5d-677ab236f206'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='uid',
            field=models.CharField(default=uuid.UUID('67959787-badc-46fb-970f-d15e5153339b'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='uid',
            field=models.CharField(default=uuid.UUID('5a7bc20f-f23e-47e4-8b5d-612c021fbfb9'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productattachment',
            name='uid',
            field=models.CharField(default=uuid.UUID('37361452-93a9-4372-9024-295706b8dd35'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='uid',
            field=models.CharField(default=uuid.UUID('51b19993-490e-44cf-bc1d-f65c23144544'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='uid',
            field=models.CharField(default=uuid.UUID('f2ba2bb3-b67b-4832-b95b-f68ddcbd20b7'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='uid',
            field=models.CharField(default=uuid.UUID('cf5c5e4b-e764-4094-bf2a-8d0a200fc590'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productordertodeliverystatus',
            name='uid',
            field=models.CharField(default=uuid.UUID('6847997c-7540-4416-8b6e-4c2873835274'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default=uuid.UUID('2316c976-6c9b-4925-9233-78e9a531b34a'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='uid',
            field=models.CharField(default=uuid.UUID('aef896d8-8200-4e73-bda7-f301648bad01'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='uid',
            field=models.CharField(default=uuid.UUID('0d077975-a1c0-437e-bc3f-ee175d93f12b'), max_length=100, primary_key=True, serialize=False),
        ),
    ]
