# Generated by Django 4.2 on 2024-03-31 17:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_alter_cartitem_uid_alter_errorlog_request_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='uid',
            field=models.CharField(default=uuid.UUID('a27d628d-d7be-4eac-bdbd-dc1ad9f1ee2a'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='uid',
            field=models.CharField(default=uuid.UUID('04593d5b-b462-4a2f-97c5-1ab15525dae7'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='uid',
            field=models.CharField(default=uuid.UUID('62b7987f-4e1d-4a41-baa5-02d63cb109bf'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='uid',
            field=models.CharField(default=uuid.UUID('a534d0b4-0013-4b6f-bec3-0844121339a9'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='uid',
            field=models.CharField(default=uuid.UUID('6398426b-454f-4e26-a7fb-255632a529e0'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='uid',
            field=models.CharField(default=uuid.UUID('82dd0c83-c67c-49d3-99cf-494311f8f3ae'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productattachment',
            name='uid',
            field=models.CharField(default=uuid.UUID('78674417-1692-4845-a5f9-054b9699fb0a'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='uid',
            field=models.CharField(default=uuid.UUID('1a13cb38-f515-4e10-8eb0-2607c78c2a98'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='uid',
            field=models.CharField(default=uuid.UUID('f4ef0e34-8d59-436d-9089-064ae4896f24'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='uid',
            field=models.CharField(default=uuid.UUID('94258432-16fc-44fd-a909-dd437a4e8875'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productordertodeliverystatus',
            name='uid',
            field=models.CharField(default=uuid.UUID('a2f644b9-4a20-4c9e-881a-86c960156b15'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default=uuid.UUID('733d59a3-968e-4e14-bdca-0857cfdc73fd'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='uid',
            field=models.CharField(default=uuid.UUID('5d62c434-57f1-4c03-85f4-15274bc534c4'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='uid',
            field=models.CharField(default=uuid.UUID('83fd904a-fc04-4257-812e-dbda3683705d'), max_length=100, primary_key=True, serialize=False),
        ),
    ]
