# Generated by Django 4.2 on 2024-03-31 17:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_alter_cartitem_uid_alter_errorlog_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='uid',
            field=models.CharField(default=uuid.UUID('18c90ade-2501-459e-9564-a900e5c08d46'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='uid',
            field=models.CharField(default=uuid.UUID('0f27febf-89bc-4821-bd78-e21ad77e4432'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='uid',
            field=models.CharField(default=uuid.UUID('42f3cbe1-5fc8-4d30-b3f5-cec1ef2c6b6f'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='uid',
            field=models.CharField(default=uuid.UUID('7c6b2cb8-9318-43f0-a83a-f42af95a8eb9'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='uid',
            field=models.CharField(default=uuid.UUID('db8ad8fd-4e5c-44f8-841e-f8d3ed619cd4'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='uid',
            field=models.CharField(default=uuid.UUID('39ff1e07-2a8f-4184-9885-08702e64667f'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productattachment',
            name='file',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='productattachment',
            name='uid',
            field=models.CharField(default=uuid.UUID('4175e3cd-6ffb-442d-bd13-2a705ef4ebe2'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='uid',
            field=models.CharField(default=uuid.UUID('a4716b5c-cc82-4c28-89bc-b2fe8fefb96b'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='uid',
            field=models.CharField(default=uuid.UUID('4dd341d7-20de-4a35-b814-79df93b33e0c'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='uid',
            field=models.CharField(default=uuid.UUID('b782af98-69c0-47f5-b326-85c2ba1df36a'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productordertodeliverystatus',
            name='uid',
            field=models.CharField(default=uuid.UUID('c6ce0ab5-59f8-41d8-90ca-1e29e97c9367'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default=uuid.UUID('5eb5728a-9c98-4f7e-854f-fc4a652035d9'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='uid',
            field=models.CharField(default=uuid.UUID('7db4afbd-6626-46d4-8b5c-2746949df31d'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='uid',
            field=models.CharField(default=uuid.UUID('5d820790-0ae0-487f-b526-c9a6fbf3ba72'), max_length=100, primary_key=True, serialize=False),
        ),
    ]
