# Generated by Django 4.2 on 2024-04-14 13:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_alter_cartitem_uid_alter_errorlog_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='uid',
            field=models.CharField(default=uuid.UUID('059ba9f8-aa2c-4b9a-a4d5-81ca10848653'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='uid',
            field=models.CharField(default=uuid.UUID('929921a2-e96d-469e-adbf-960991a3bd23'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='uid',
            field=models.CharField(default=uuid.UUID('f4928adb-5fd6-4e24-8aae-b58494167402'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='uid',
            field=models.CharField(default=uuid.UUID('b73fff4f-b336-4f13-ad18-410e04d223da'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='uid',
            field=models.CharField(default=uuid.UUID('599b3422-fdce-414c-9ba8-db1f51bbb070'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='uid',
            field=models.CharField(default=uuid.UUID('77798cde-f3e2-47fb-82bb-6490c645cc2f'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productattachment',
            name='uid',
            field=models.CharField(default=uuid.UUID('afe5aabc-d0d0-419d-881f-13adbf2509cd'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='uid',
            field=models.CharField(default=uuid.UUID('37900304-c9bf-4e03-a096-3815e94163e5'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='uid',
            field=models.CharField(default=uuid.UUID('c567ad16-669d-4d79-824c-d07e13d64b0c'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='uid',
            field=models.CharField(default=uuid.UUID('ec95912d-6064-4240-adad-e18b52a6e16d'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productordertodeliverystatus',
            name='uid',
            field=models.CharField(default=uuid.UUID('9ff3207c-e461-4493-8bff-df1b0bed9a7f'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default=uuid.UUID('3b113c2d-032b-48d2-87a7-e6a2b5e105e4'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='uid',
            field=models.CharField(default=uuid.UUID('41ba8c59-11a8-4be5-8912-653088503b26'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='uid',
            field=models.CharField(default=uuid.UUID('a92ae23c-f974-48b2-b325-4138968b5b0d'), max_length=100, primary_key=True, serialize=False),
        ),
    ]
