# Generated by Django 4.2 on 2024-04-19 04:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0016_alter_cartitem_uid_alter_errorlog_uid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('uid', models.CharField(default='627f43bacea3445a9f2817000f52b75d171350123126138', max_length=100, primary_key=True, serialize=False)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('user_type', models.CharField(blank=True, max_length=255, null=True)),
                ('request_method', models.CharField(blank=True, max_length=255, null=True)),
                ('request_headers', models.TextField(blank=True, null=True)),
                ('request_parameters', models.CharField(blank=True, max_length=255, null=True)),
                ('request_body', models.TextField(blank=True, null=True)),
                ('client_ip', models.CharField(blank=True, max_length=255, null=True)),
                ('view_name', models.CharField(blank=True, max_length=255, null=True)),
                ('response_status_code', models.CharField(blank=True, max_length=255, null=True)),
                ('environment', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('response_content', models.TextField(blank=True, null=True)),
                ('request_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=1000, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('referer', models.URLField(blank=True, max_length=2000, null=True)),
                ('request_query_params', models.JSONField(blank=True, null=True)),
                ('response_headers', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='uid',
            field=models.CharField(default='7cce139fd5034e5ebd45209a0ffc5889171350123166995', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='uid',
            field=models.CharField(default='188a3483a45b479eb67429feb4da8956171350123137716', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='uid',
            field=models.CharField(default='1dd664f42b294a15890dc45040ef6f8e171350123133302', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='uid',
            field=models.CharField(default='effc479156fc4d4fb480c981cb4e091a171350123132731', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='uid',
            field=models.CharField(default='435d5db815874961a44d9efaddbd2d7d171350123183037', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='uid',
            field=models.CharField(default='8eea0130bfb74fa4ae0a674d782551cf171350123169551', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productattachment',
            name='uid',
            field=models.CharField(default='ba2f16882cd74b3bab04fb346ce1f436171350123159297', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='uid',
            field=models.CharField(default='b3c35d26084e42fdb4765cbbbac9b570171350123151050', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='uid',
            field=models.CharField(default='f1bb1be289ad453d8feb5721213b23d0171350123174519', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='uid',
            field=models.CharField(default='579261d25ee0400e80e107bd1af6f701171350123160304', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productordertodeliverystatus',
            name='uid',
            field=models.CharField(default='1244a9bdd86f41ae98b89cd0269d31df171350123141164', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default='d856701dc6024056b0133e466820639f171350123176508', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='uid',
            field=models.CharField(default='d31f74538d554beaa503f1dd0a0c8fbf171350123120887', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='uid',
            field=models.CharField(default='800cdd0cd9074bc4834c096ff380809e171350123127466', max_length=255, primary_key=True, serialize=False),
        ),
    ]
