# Generated by Django 4.2 on 2024-04-19 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0018_productcategoryvarient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantOptions',
            fields=[
                ('uid', models.CharField(default='0a7c647e977148acb12e29a71b485e96171353951082649', max_length=255, primary_key=True, serialize=False)),
                ('varient_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VarientAttribute',
            fields=[
                ('uid', models.CharField(default='6f87f1663ee143dbb381c55daac8a9be171353951020896', max_length=255, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=255)),
                ('options', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varient_options', to='apps.variantoptions')),
            ],
        ),
        migrations.RenameField(
            model_name='productvarient',
            old_name='product_price',
            new_name='product_price_adjustment',
        ),
        migrations.RemoveField(
            model_name='productvarient',
            name='varient',
        ),
        migrations.RemoveField(
            model_name='productvarient',
            name='varient_value',
        ),
        migrations.AddField(
            model_name='product',
            name='product_discount',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_discount', to='apps.productdiscount'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='uid',
            field=models.CharField(default='f5ad70531f4e46e4bb5d402928ae26d1171353951049086', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='uid',
            field=models.CharField(default='31da03cc25af4ff9abfea1024edc226a171353951088968', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='uid',
            field=models.CharField(default='015c2c6336384b8badeab7e8bed5feef171353951079932', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='uid',
            field=models.CharField(default='23f3d1ba27ab4303b51ec535ed02bafd171353951029234', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='uid',
            field=models.CharField(default='cb44c8c1656043f5a45e4594232896ed171353951036801', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='uid',
            field=models.CharField(default='a1620e5f507a45ecb83564b7a739cb9b171353951081306', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='uid',
            field=models.CharField(default='6fa29ed491844f09bbca11b3af02dc62171353951037614', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productattachment',
            name='uid',
            field=models.CharField(default='2f7299bd42624f968ae08d1857c72b3b171353951012408', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='uid',
            field=models.CharField(default='ff0f202401bd4342aa9b66c4366da1e8171353951085582', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='uid',
            field=models.CharField(default='0612bcbc04aa4c4395d47d1e13652acd171353951069005', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='uid',
            field=models.CharField(default='733ff7630ef747b79f13346785ca4669171353951096054', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productordertodeliverystatus',
            name='uid',
            field=models.CharField(default='9347350b5ac84a68813f05f86c881772171353951078737', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productvarient',
            name='product_discount',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='varient_discount', to='apps.productdiscount'),
        ),
        migrations.AlterField(
            model_name='productvarient',
            name='uid',
            field=models.CharField(default='4b23f648970341dca23844e5597b3c2c171353951043326', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default='c35daeb57be24f69a9b24039aa6dc050171353951082611', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='uid',
            field=models.CharField(default='03658b4ae8994d97b52448055e769cd3171353951047729', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='uid',
            field=models.CharField(default='1a7bfcc9f8564b529c36106a6a01e4e6171353951065888', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='ProductCategoryVarient',
        ),
        migrations.AddField(
            model_name='varientattribute',
            name='varient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_varient', to='apps.productvarient'),
        ),
        migrations.AddField(
            model_name='variantoptions',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_variants', to='apps.productcategory'),
        ),
    ]
