# Generated by Django 4.2 on 2024-04-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0019_variantoptions_varientattribute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='uid',
            field=models.CharField(default='a811cfd8a2174dfeb1bccf609c2f6603171353984246348', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='uid',
            field=models.CharField(default='a8b518075ab24e54bae3a7987b31b96e171353984213420', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='uid',
            field=models.CharField(default='8bbe0b9ac0f443a8bec89b7fc8a998a8171353984273602', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='uid',
            field=models.CharField(default='ead7ce99e8904e7f9993a5a1a9a7a83b171353984217034', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='uid',
            field=models.CharField(default='717ee5afa92547bfaaea6500c40c2a9f171353984244196', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='uid',
            field=models.CharField(default='fea7bfc62f024c669eb3ca576a3fc8c1171353984258688', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='uid',
            field=models.CharField(default='3a99051a246f413db01f3a99f8d7f404171353984299095', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productattachment',
            name='uid',
            field=models.CharField(default='f38db8fbe3ca41af816f70e5a4999a12171353984225802', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='uid',
            field=models.CharField(default='6df2a5d5766a4fe1bb87ec15162d8cfd171353984291100', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='uid',
            field=models.CharField(default='3cde4f1d8df84410bd9bf258561ccc14171353984248260', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='uid',
            field=models.CharField(default='de81f6f128644e38b4d4ae81161627d7171353984241096', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productordertodeliverystatus',
            name='uid',
            field=models.CharField(default='038b0f2cb0f44bc584901b3c8ccfd261171353984255537', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productvarient',
            name='uid',
            field=models.CharField(default='46e781685f4f48d0a61577cbed62d4dd171353984272060', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default='bb2746968d6f4097b6a6f09279885999171353984215504', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='uid',
            field=models.CharField(default='edeffb832ccd4558aaded5047c068b93171353984221268', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='uid',
            field=models.CharField(default='c17d271bdf7f45aca99cfc43988291fb171353984233848', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='variantoptions',
            name='uid',
            field=models.CharField(default='82f48df1f89546739ce2fc03b5c638b1171353984298807', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='varientattribute',
            name='uid',
            field=models.CharField(default='9da38e003d8c46318d0ef061349924a6171353984227755', max_length=255, primary_key=True, serialize=False),
        ),
    ]
