# Generated by Django 4.2 on 2024-04-20 04:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0021_rename_product_discount_productvarient_varient_discount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('uid', models.CharField(default='9a362045e52b48d981888cbe759aabe6171358833883003', max_length=255, primary_key=True, serialize=False)),
                ('brand_name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='uid',
            field=models.CharField(default='5d4c64eff9af402d9aacb9d6efbf56d4171358833821802', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='uid',
            field=models.CharField(default='f42b02f253fa4cce813ef4200fd2ecc1171358833892795', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='uid',
            field=models.CharField(default='863db1ad507f4c89b1f4a94b33fa249e171358833823694', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='uid',
            field=models.CharField(default='9ec40a1b0b97475aafd5e6750f5bc8ec171358833836145', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='uid',
            field=models.CharField(default='c06703f1a93b41b3b14b010e1db0a121171358833898174', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='uid',
            field=models.CharField(default='fda0ef0e32484393916dfb6d406acb53171358833870948', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='category', to='apps.productcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_discount',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='product_discount', to='apps.productdiscount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='uid',
            field=models.CharField(default='77fb5d868f204d4e97abecfc4631a924171358833828596', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productattachment',
            name='uid',
            field=models.CharField(default='3099216c6e4746c9a3c1b42ed0f38236171358833840456', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='uid',
            field=models.CharField(default='ed5f8ca33a2c4038bd1376d45dbf3b6f171358833851967', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='uid',
            field=models.CharField(default='7828b2881e1a4c2585ea58e0f809d46b171358833853836', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='uid',
            field=models.CharField(default='54d7b0277e24448cbc39bb8a117a201d171358833836071', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productordertodeliverystatus',
            name='uid',
            field=models.CharField(default='a5ff8a3a4d7b4940abc6900eed241432171358833894764', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productvarient',
            name='product_inventory',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='inventory', to='apps.productinventory'),
        ),
        migrations.AlterField(
            model_name='productvarient',
            name='uid',
            field=models.CharField(default='655cb95cb7cb4b5381222c4f990f464e171358833868764', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productvarient',
            name='varient_discount',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='varient_discount', to='apps.productdiscount'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default='c0efbdc9822d4fc2b81961f5169d3cb4171358833884554', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='uid',
            field=models.CharField(default='150f82e28334429b97f7c3b81b41f643171358833835531', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='uid',
            field=models.CharField(default='123aca660d504cc48d33f4d5b30fefb1171358833821109', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='variantoptions',
            name='uid',
            field=models.CharField(default='471638808a214e8db66a77f1e7e7778c171358833823174', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='varientattribute',
            name='uid',
            field=models.CharField(default='49b1debad86c4fa79bb045095c3db0e8171358833849131', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_brand',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='apps.productbrand'),
        ),
    ]
