# Generated by Django 4.2 on 2024-04-20 07:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0022_productbrand_alter_accesslog_uid_alter_cartitem_uid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvarient',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='productvarient',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='productvarient',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productvarient',
            name='modified_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='variantoptions',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='variantoptions',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='variantoptions',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='variantoptions',
            name='modified_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='varientattribute',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='varientattribute',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='varientattribute',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='varientattribute',
            name='modified_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='uid',
            field=models.CharField(default='6daae950ac34465e86da499936d130e9171359783668155', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='uid',
            field=models.CharField(default='de832c4448134428b4f5e11b9773bdb8171359783681522', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='uid',
            field=models.CharField(default='7bc2c6d2892e4033a17195b7773ad516171359783693108', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='uid',
            field=models.CharField(default='51d353ac146345f6bf6abda7c6d2251d171359783621246', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='uid',
            field=models.CharField(default='1776c12361b54a6ebb70a23e27075ee7171359783688174', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='uid',
            field=models.CharField(default='c262f3d73318447999a84dd8b36779f6171359783659932', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='uid',
            field=models.CharField(default='4ecaef006f004fc294311bc6c16010d3171359783687636', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productattachment',
            name='uid',
            field=models.CharField(default='e2975cf360694a87ab675b79d1049c45171359783653418', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productbrand',
            name='uid',
            field=models.CharField(default='329b54a0456348e48d93a875040b6006171359783613854', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='uid',
            field=models.CharField(default='3bc9f709450d412f8bb867d167f5a4d4171359783624582', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='uid',
            field=models.CharField(default='6b1c1cea90404336a2e02d0068dc9f39171359783679830', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='uid',
            field=models.CharField(default='98f1ecedeee14ada879bb8a78cade374171359783675507', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productordertodeliverystatus',
            name='uid',
            field=models.CharField(default='3908ea3a5f1a4df1a5cc81d77d94ded3171359783699318', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productvarient',
            name='uid',
            field=models.CharField(default='46abb4bbab5e4902b6c4df0706a61d53171359783647031', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default='2ca7fd1245704000a3dd8c14708797db171359783642187', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='uid',
            field=models.CharField(default='7db561bde22947529a78e77003c56098171359783637291', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='uid',
            field=models.CharField(default='1538068c574245348dcfa1de1d57ce32171359783647412', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='variantoptions',
            name='uid',
            field=models.CharField(default='0523fd787b9c4dc69f9f7f6b2622e5e9171359783664263', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='varientattribute',
            name='uid',
            field=models.CharField(default='ce552d86f8a84d70b5ce8abb8d057448171359783675420', max_length=255, primary_key=True, serialize=False),
        ),
    ]
