# Generated by Django 4.2 on 2024-04-20 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0024_invoice_invoice_for_payment_user_product_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='uid',
            field=models.CharField(default='a4e39e6374ff4cbfaaa028279f9bffc4171362166589599', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='uid',
            field=models.CharField(default='533848f748244ee8aeab4b663e34b101171362166551895', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='uid',
            field=models.CharField(default='6bd5cc36428f44edb0c07e0162790434171362166554101', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='uid',
            field=models.CharField(default='202b9a8b433846788b12be911210c094171362166515465', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='uid',
            field=models.CharField(default='6c0792d770614a05857460cfb9ec245b171362166593807', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='uid',
            field=models.CharField(default='45a26db0b3424b8dab11e4857b38ba58171362166577670', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='product_user', to='apps.user'),
        ),
        migrations.AlterField(
            model_name='product',
            name='uid',
            field=models.CharField(default='80586d725a9f478d8253546ab55b1afc171362166554914', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productattachment',
            name='uid',
            field=models.CharField(default='fe35a9417e9e47c1be758f1328178347171362166584728', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productbrand',
            name='created_by',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='brand_user', to='apps.user'),
        ),
        migrations.AlterField(
            model_name='productbrand',
            name='uid',
            field=models.CharField(default='52aeaaf8aa7d4d8194592541f10c4789171362166556418', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='created_by',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='category_user', to='apps.user'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='uid',
            field=models.CharField(default='7f9bc0d26b9148aeba861a3d12990f50171362166597690', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='created_by',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='discount_user', to='apps.user'),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='uid',
            field=models.CharField(default='212390a4d0ab40ba901563c4f8177fda171362166516250', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='created_by',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='inventory_user', to='apps.user'),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='uid',
            field=models.CharField(default='67c815ef78844b0d8cb2eda617eec56c171362166572688', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productordertodeliverystatus',
            name='uid',
            field=models.CharField(default='d838511182694b20827964a53bf1fe30171362166552536', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productvarient',
            name='uid',
            field=models.CharField(default='d5b8577ef7a8412ebe17013aa7c60ad3171362166575638', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default='a81762a68620489aa3d2c0f4a8ef6ae0171362166524495', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='uid',
            field=models.CharField(default='0a8775274154487f91a48edb26d42e91171362166560516', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='uid',
            field=models.CharField(default='bc845bd37db54e36b713790aca1728ea171362166545347', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='variantoptions',
            name='uid',
            field=models.CharField(default='76143e53df8e417189694c1e008d6bc7171362166569333', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='varientattribute',
            name='uid',
            field=models.CharField(default='2bc5be58267649bc8b4a7e22681c9fc3171362166521359', max_length=255, primary_key=True, serialize=False),
        ),
    ]
