# Generated by Django 4.2 on 2024-04-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0026_alter_accesslog_uid_alter_cartitem_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='uid',
            field=models.CharField(default='3655cfa9343a430c89f9eb69d2d233d0171362199684923', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='uid',
            field=models.CharField(default='a14d2f477ba04773874b96cfc57683cc171362199680031', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='uid',
            field=models.CharField(default='7ab8fba01d5d45fab11a3ff7ad263181171362199665960', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='uid',
            field=models.CharField(default='a9c00fe658c54a65b18c08eb68b4c0b7171362199679565', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='uid',
            field=models.CharField(default='49d3c37fefb140c4ad9c1a8d5e75b987171362199619817', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='uid',
            field=models.CharField(default='fbd6e2f3c5ac4adfa74ff74ef85511ef171362199688898', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='uid',
            field=models.CharField(default='6805c33a1bb74f5881d3850b0c56d15c171362199612605', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productattachment',
            name='uid',
            field=models.CharField(default='799653388ef74542b52ff904732c0e6a171362199676111', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productbrand',
            name='uid',
            field=models.CharField(default='de8601afeb264af08483f73bce1591bc171362199662243', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='uid',
            field=models.CharField(default='594e8f811a294c24afb7df98554728b9171362199693586', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='uid',
            field=models.CharField(default='eef74ca519a84b6298e464f1eb0d2d2d171362199683118', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='uid',
            field=models.CharField(default='17461f54cd0347df93446e4b69fea820171362199659648', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productordertodeliverystatus',
            name='uid',
            field=models.CharField(default='2964469ea78f4d83a1a7885788070b82171362199690939', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productvarient',
            name='uid',
            field=models.CharField(default='63208a4932d04ec9b58084e7ff260377171362199666421', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default='d7d939b030b647caa3f806f0cacf23e1171362199685831', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='uid',
            field=models.CharField(default='4cfd89a777ed4f7b965c990111ed9318171362199699205', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='uid',
            field=models.CharField(default='fcbc93b44cc04eb3b4a797e032f014bc171362199629825', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='variantoptions',
            name='uid',
            field=models.CharField(default='b8525e1393cc40a294a73f6f392b8f52171362199676832', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='varientattribute',
            name='uid',
            field=models.CharField(default='7752a809559f483397f71fd93eadd93d171362199666002', max_length=255, primary_key=True, serialize=False),
        ),
    ]
