# Generated by Django 4.2 on 2024-04-28 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0027_alter_accesslog_uid_alter_cartitem_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='uid',
            field=models.CharField(default='8d5ebbf847a6413282ccc3155c3cdee3171427454244137', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='uid',
            field=models.CharField(default='8cf23f93717b4702b5da031911e8ab63171427454254222', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='uid',
            field=models.CharField(default='0f7a4c1d21684bdfbfae2c36f66e1a6b171427454232962', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='uid',
            field=models.CharField(default='9a47c11d006d400c9dedb56af53e34cb171427454233310', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='uid',
            field=models.CharField(default='3f6a939f387045d6bb9e82643a0ff7e9171427454261749', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='uid',
            field=models.CharField(default='f52d22be13734a2cad092d39ee78953b171427454216156', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='uid',
            field=models.CharField(default='491597a1210f4f4bbea1e63019cc3a9b171427454278910', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productattachment',
            name='uid',
            field=models.CharField(default='fec0ba01d8c744539b1984a737a6ad93171427454233904', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productbrand',
            name='uid',
            field=models.CharField(default='dd563cc5eead4168972caa08a3ab4549171427454265194', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='category_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='uid',
            field=models.CharField(default='56d2a41172df420084b67165330fb705171427454295802', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='uid',
            field=models.CharField(default='0cb422f0dbe84335aa39e3e501e17d84171427454288985', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='uid',
            field=models.CharField(default='fc71eb05d2fe43d1b010cf2eb3e80994171427454262320', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productordertodeliverystatus',
            name='uid',
            field=models.CharField(default='2c0c040965524b228b2627ce75e852a9171427454225184', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productvarient',
            name='uid',
            field=models.CharField(default='245f29fda3544c61aa72ad1a21c9bf4a171427454293343', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default='949013f915504eb592369a5d3bfa2255171427454263818', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='uid',
            field=models.CharField(default='0ec1b573e1c4420bad5232559e12d251171427454253847', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='uid',
            field=models.CharField(default='47998b8bf3c744b98c87931b390ed2d4171427454231745', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='variantoptions',
            name='uid',
            field=models.CharField(default='6bc7b2c77d1c4ddda653634887ee56be171427454216994', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='varientattribute',
            name='uid',
            field=models.CharField(default='18568a5303dc42a5bde88ed354df7b17171427454226814', max_length=255, primary_key=True, serialize=False),
        ),
    ]
