# Generated by Django 4.2 on 2024-05-01 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0028_alter_accesslog_uid_alter_cartitem_uid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbrand',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='uid',
            field=models.CharField(default='23144d143d12406f84d6cc89f9a421d3171454777256749', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='uid',
            field=models.CharField(default='4c5a8234c5ff40fcaec108952d4f4e43171454777216303', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='uid',
            field=models.CharField(default='5170b0055f0d4a1a8f5468b0cb9c2650171454777233054', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='uid',
            field=models.CharField(default='8fb80da76da64fe593f092366d0898ac171454777294615', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='uid',
            field=models.CharField(default='91fe98b747ef4e64bf1e57e83040587d171454777263687', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='uid',
            field=models.CharField(default='bd3e7c5e4e074e7cb6e9f4115d455a88171454777263470', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='uid',
            field=models.CharField(default='cf8e9c1bf0e84fd4955c571ae13a2c89171454777293653', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productattachment',
            name='uid',
            field=models.CharField(default='e4c6360bc18c40f7af3de5511c0124ed171454777241073', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productbrand',
            name='uid',
            field=models.CharField(default='3d15862534c54ffdb5fb394d90435247171454777255905', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='uid',
            field=models.CharField(default='1b5ca615e5444473ac51bb40f77b537b171454777232894', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='uid',
            field=models.CharField(default='135eb39497f64910a7b31812b3b11e2e171454777228704', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='uid',
            field=models.CharField(default='87e79d0fe23447559f853c3b4155fcbb171454777247045', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productordertodeliverystatus',
            name='uid',
            field=models.CharField(default='f6fb3f6c40754f9faad8d9b991ad614e171454777237161', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productvarient',
            name='uid',
            field=models.CharField(default='7f93c79e405d4580ab50012fe49e1079171454777256940', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default='fc362c888e614576af113682d513cbe6171454777211185', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='uid',
            field=models.CharField(default='7e3d670edc9d4644a94d997446190917171454777256384', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='uid',
            field=models.CharField(default='603e11ddc7e84b6c8231c8aabf10bfdb171454777250473', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='variantoptions',
            name='uid',
            field=models.CharField(default='6be2439748624818b7f8e18c0fbd31fe171454777282979', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='varientattribute',
            name='uid',
            field=models.CharField(default='501b34f09e0148c682417534670ec549171454777281683', max_length=255, primary_key=True, serialize=False),
        ),
    ]
