# Generated by Django 4.2 on 2024-05-01 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0029_productbrand_image_productcategory_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbrand',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='brand_category', to='apps.productcategory'),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='uid',
            field=models.CharField(default='2cf83427a5c14b8cab7eaca7fdd25951171455250290692', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='uid',
            field=models.CharField(default='e4b88f9ef5454c57a5471c8c253b6d54171455250271393', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='uid',
            field=models.CharField(default='ce3abb98d30c45f480cc6c445730fc4a171455250292401', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='uid',
            field=models.CharField(default='e5364e530acf450fb9d3eb434967b547171455250216494', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='uid',
            field=models.CharField(default='897759b1217f4ff3a7d50c7023406996171455250269438', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='uid',
            field=models.CharField(default='f17df476342749a79ef90f32c654822c171455250293833', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='uid',
            field=models.CharField(default='71893dc293a44d5b9ff05211b56e9476171455250255686', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productattachment',
            name='uid',
            field=models.CharField(default='66c68a49d8fb44d4953a7244c4b024a1171455250248955', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productbrand',
            name='uid',
            field=models.CharField(default='af65008c68fa43b88d669276c76e67fd171455250231724', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='uid',
            field=models.CharField(default='d710e1698c754d4d9028b2d26810fb8e171455250212995', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='uid',
            field=models.CharField(default='b60ddeb8e3d04541b7b3d0a04398acc0171455250231352', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='uid',
            field=models.CharField(default='1fb4be57ab2e4f66b4cd3e5c9b8958dd171455250258624', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productordertodeliverystatus',
            name='uid',
            field=models.CharField(default='ca2658d2b0a543619b32a71980ec5822171455250268191', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productvarient',
            name='uid',
            field=models.CharField(default='778a3ba454944962bb81ba76ed920635171455250237287', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default='d6fba88e61804ec6b404812d33a5efd5171455250212733', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='uid',
            field=models.CharField(default='2211247a2ae84fc6a12f771a1a42d227171455250286553', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='uid',
            field=models.CharField(default='92e51f31876940c88898caffac5a811d171455250239023', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='variantoptions',
            name='uid',
            field=models.CharField(default='da63bde4794e4fc38c54c2ccc9a75dd1171455250283001', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='varientattribute',
            name='uid',
            field=models.CharField(default='33738e0e1bb8434bae8e7e797216cb35171455250287851', max_length=255, primary_key=True, serialize=False),
        ),
    ]
