# Generated by Django 4.2 on 2024-05-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0030_productbrand_category_alter_accesslog_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='uid',
            field=models.CharField(default='035fd2f7dfbe46a7a06e244cc48a5efd171455832496882', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='uid',
            field=models.CharField(default='e437fdf0ee6f4876b415e45a721427df171455832418303', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='uid',
            field=models.CharField(default='d68853d2f31c4af688914f79fb344826171455832419680', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='uid',
            field=models.CharField(default='b7a331d53016422f877cbf135372d9d0171455832448698', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='uid',
            field=models.CharField(default='23e454dae35e416c87d77d926a81f752171455832460620', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='uid',
            field=models.CharField(default='b9ea63219beb4bd29c5cb13816280e80171455832419725', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='uid',
            field=models.CharField(default='9216343b914c466981043fbb5803d1ee171455832417640', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productattachment',
            name='uid',
            field=models.CharField(default='2083927034924c24aeedfdb064838451171455832428089', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productbrand',
            name='brand_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='productbrand',
            name='uid',
            field=models.CharField(default='217b1349825e4477b7e4ed72528bb07b171455832442085', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='uid',
            field=models.CharField(default='5e3432dd53644f74b4be8fb870b55943171455832417503', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='uid',
            field=models.CharField(default='c073c7584c354956a2bd15a18a28ead3171455832494608', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='uid',
            field=models.CharField(default='5de99b6fd40d4258aba0383f5d7ab4e4171455832431676', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productordertodeliverystatus',
            name='uid',
            field=models.CharField(default='68c7692a7dc248de8a09ca984767c775171455832451338', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productvarient',
            name='uid',
            field=models.CharField(default='bdd12c5bb52d4dee92019e01e500dd17171455832436408', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default='dab4b283acb44f509e809ba5d4397562171455832483052', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='uid',
            field=models.CharField(default='aa159383569d49e198e7c7a4cf274134171455832453124', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='uid',
            field=models.CharField(default='afed62bf78244947bffbe12a4ab49eef171455832447813', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='variantoptions',
            name='uid',
            field=models.CharField(default='6892eea1003b4058bc6bd95778efae34171455832448150', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='varientattribute',
            name='uid',
            field=models.CharField(default='b67aaa7a1acd48d39bc295b22580fc5f171455832416652', max_length=255, primary_key=True, serialize=False),
        ),
    ]
